#!/bin/zsh

NAME="../minishell"
# norminette -C ..
# make -C ..
# make clean -C ..
# make fclean -C ..
# make re -C ..

# ctrl c dois mettre errno à 1

# make re CFLAGS+=$CFLAGS" -fsanitize=address -g3" -C ..
make re DEBUG=1 -C ..

waitKeypress () {
    echo "Press any key to continue"
    while [ true ]
    do
        read -t 3 -n 1
        if [ $? = 0 ] ; then
            break ;
        fi
    done
}

echo -e "\n\n\n====================================== Simple Command & global variables ======================================\n\n\n"
cat eval/"Simple Command & global variables"|$NAME
waitKeypress

echo -e "\n\n\n====================================== Arguments & history ======================================\n\n\n"
cat eval/"Arguments & history"|$NAME
waitKeypress

echo -e "\n\n\n====================================== echo ======================================\n\n\n"
cat eval/"echo"|$NAME
waitKeypress

echo -e "\n\n\n====================================== exit ======================================\n\n\n"

echo "exit"|$NAME
echo "exit 0"|$NAME
echo "exit skj"|$NAME
echo -e "exit 1 2 3 4\nexit 1 2 3 a"|$NAME

echo -e "\n\n\n====================================== Return value of a process ======================================\n\n\n"
cat eval/"Return value of a process"|$NAME
waitKeypress

echo -e "\n\n\n====================================== Signals ======================================\n\n\n"

echo try your own test

echo -e "\n\n\n====================================== Double Quotes ======================================\n\n\n"
cat eval/"Double Quotes"|$NAME
waitKeypress

echo -e "\n\n\n====================================== Single Quotes ======================================\n\n\n"
cat eval/"Single Quotes"|$NAME
waitKeypress

echo -e "\n\n\n====================================== export & env ======================================\n\n\n"
cat eval/"export & env"|$NAME
waitKeypress

echo -e "\n\n\n====================================== unset ======================================\n\n\n"
cat eval/"unset"|$NAME
waitKeypress

echo -e "\n\n\n====================================== cd & pwd ======================================\n\n\n"
cat eval/"cd & pwd"|$NAME
waitKeypress

echo -e "\n\n\n====================================== Relative Path ======================================\n\n\n"
cat eval/"Relative Path"|$NAME
waitKeypress

echo -e "\n\n\n====================================== Environment path ======================================\n\n\n"
cat eval/"Environment path"|$NAME
waitKeypress

echo -e "\n\n\n====================================== Redirection ======================================\n\n\n"
cat eval/"Redirection"|$NAME
waitKeypress

echo -e "\n\n\n====================================== Pipes ======================================\n\n\n"
cat eval/"Pipes"|$NAME
waitKeypress

echo -e "\n\n\n====================================== Go Crazy and history ======================================\n\n\n"
cat eval/"Go Crazy and history"|$NAME
waitKeypress

echo -e "\n\n\n====================================== Environment variables ======================================\n\n\n"
cat eval/"Environment variables"|$NAME
waitKeypress
echo -e "\n\n\n====================================== END ======================================\n\n\n"
rm out*
rm dupMakefile
rm hello
